# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Think < Formula
  desc "AI-Assisted Command Line Mastery"
  homepage "https://github.com/ryszard/think"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryszard/think/releases/download/v0.0.8/think_Darwin_x86_64.tar.gz"
      sha256 "9665f40a09171c9b7e66b07f6abec4381adbb88544153fc99453ef16af518fef"

      def install
        bin.install "think"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryszard/think/releases/download/v0.0.8/think_Darwin_arm64.tar.gz"
      sha256 "fec94d073a2059c2f6c4131c06fca1e324e4019b234fa737df333fba72fd74be"

      def install
        bin.install "think"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryszard/think/releases/download/v0.0.8/think_Linux_arm64.tar.gz"
      sha256 "8efdfa0b14625cfaf1271c6de6c8e748b831c4a5f4ffbab8e9048118ea9e456a"

      def install
        bin.install "think"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryszard/think/releases/download/v0.0.8/think_Linux_x86_64.tar.gz"
      sha256 "e1b7d740e7d613c7b67e6a9a0191cc46a2f0e988bd4fa2ac8782579e77360830"

      def install
        bin.install "think"
      end
    end
  end
end
