# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Think < Formula
  desc "AI-Assisted Command Line Mastery"
  homepage "https://github.com/ryszard/think"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryszard/think/releases/download/v0.0.11/think_Darwin_x86_64.tar.gz"
      sha256 "ca3d1c91f6805e1efcfb499e13728102e36de581af0b5fe1d0293f8415e7e6c2"

      def install
        bin.install "think"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryszard/think/releases/download/v0.0.11/think_Darwin_arm64.tar.gz"
      sha256 "0bce97ca9e9e15df0c987f7c08b75df75bea16433854a73b679de5b228cf6a68"

      def install
        bin.install "think"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryszard/think/releases/download/v0.0.11/think_Linux_arm64.tar.gz"
      sha256 "657b4d407b2231a6c71918261463e454259c4cfaec089004375af90d96a3d4dd"

      def install
        bin.install "think"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryszard/think/releases/download/v0.0.11/think_Linux_x86_64.tar.gz"
      sha256 "2ce4c0c6e4f68e14578f451be59b9f15e04c4d0c0a5a8117de83cc97ef0641d5"

      def install
        bin.install "think"
      end
    end
  end
end
